// <auto-generated />
using System;
using BaoTest1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaoTest1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806105736_AddTableSinhVien")]
    partial class AddTableSinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaoTest1.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLopHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("BaoTest1.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoSinhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("BaoTest1.Models.SinhVien", b =>
                {
                    b.HasOne("BaoTest1.Models.LopHoc", "LopHoc")
                        .WithMany("ListSV")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("BaoTest1.Models.LopHoc", b =>
                {
                    b.Navigation("ListSV");
                });
#pragma warning restore 612, 618
        }
    }
}
